### ISSUE TITLE
Getting Server Error (500)

### ISSUE THREAD

**Issue by karthik18495** [summarizepaper/summarizepaper#2]
A hearty congratulations to this app. I was also trying to make such an app but found this awesome app. Really being inspired. I have been trying to sign up using the login option. but I am getting Server Error (500) when trying to sign up

Any leads?

thank you

**Comment by qkral** [comment]
It was just the part sending the email that stopped working and caused a 500 server error page and it is now corrected. Your account should have been created though.

**Comment by summarizepaper** [comment]
Thanks for your message karthik it goes straight to our hearts!
